// AUTO-GENERATED by local-authority-silo-engine for Langford Staffing.
// Blog index page listing every silo blog by city.
import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import CTASection from "@/components/CTASection";
import SectionHeading from "@/components/SectionHeading";
import SchemaJsonLd from "@/components/SchemaJsonLd";
import { BRAND, NAP } from "@/lib/constants";
import { breadcrumbSchema } from "@/lib/schema";
import bundle from "@/lib/silo/content.json";

type SiloPage = {
  type: string;
  url: string;
  title: string;
  city: string;
  city_key?: string;
  state_abbr: string;
  service_label?: string;
};

const BLOGS: SiloPage[] = (bundle.pages as SiloPage[]).filter((p) => p.type === "blog");

// Group blogs by city for the index
const BY_CITY: Record<string, SiloPage[]> = {};
for (const b of BLOGS) {
  const k = b.city_key || b.city;
  BY_CITY[k] = BY_CITY[k] || [];
  BY_CITY[k].push(b);
}
const CITY_KEYS = Object.keys(BY_CITY).sort((a, b) => {
  return (BY_CITY[a][0]?.city || a).localeCompare(BY_CITY[b][0]?.city || b);
});

export const metadata = {
  title: `Local Staffing Insights | ${BRAND.name}`,
  description: `City-specific staffing market guides and hiring playbooks from ${BRAND.name}.`,
  alternates: { canonical: `${NAP.websiteUrl}/blog/` }
};

export default function BlogIndex() {
  return (
    <>
      <SchemaJsonLd
        data={[
          breadcrumbSchema([
            { name: "Home", url: NAP.websiteUrl + "/" },
            { name: "Blog", url: NAP.websiteUrl + "/blog/" }
          ])
        ]}
      />

      <section className="relative isolate overflow-hidden bg-brand-navy text-white">
        <div className="relative container-prose pt-12 pb-14 lg:pt-16 lg:pb-20">
          <p className="inline-flex items-center gap-2 border border-white/20 bg-white/5 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron">
            <MapPin className="h-3 w-3" />
            Local insights
          </p>
          <h1 className="mt-6 max-w-3xl text-display-xl font-semibold text-balance">
            Local staffing market guides,{" "}
            <em className="not-italic font-semibold text-brand-saffron">city by city.</em>
          </h1>
          <p className="mt-6 max-w-2xl text-[17px] leading-relaxed text-white/85">
            Plain English guidance on how the hiring market works in each of the
            cities Langford staffs across the United States and Canada.
          </p>
        </div>
      </section>

      <section className="section">
        <div className="container-prose space-y-10">
          {CITY_KEYS.map((k) => {
            const posts = BY_CITY[k];
            const cityName = posts[0]?.city || k;
            return (
              <div key={k}>
                <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                  {cityName}, {posts[0]?.state_abbr}
                </p>
                <h2 className="mt-2 font-display text-[20px] font-semibold text-brand-navy">
                  Guides from the {cityName} market
                </h2>
                <ul className="mt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {posts.map((b) => (
                    <li key={b.url}>
                      <Link
                        href={`${b.url}/`}
                        className="block border border-brand-line bg-white p-4 no-underline transition hover:border-brand-saffron"
                      >
                        <p className="font-semibold text-brand-navy">{b.title}</p>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            );
          })}
        </div>
      </section>

      <CTASection
        eyebrow="Talk to Langford"
        title="Hire faster across the United States and Canada."
        description="Tell us the role, the city, and the start date. We come back inside a business day."
        variant="navy"
      />
    </>
  );
}
