// IG-style sitemap INDEX: /sitemap.xml is an index pointing to chunked
// sub-sitemaps (pages / locations / services / blog), mirroring Insight
// Global's split sitemap structure. Generated by Next generateSitemaps.
import type { MetadataRoute } from "next";
import { SERVICES } from "@/lib/services";
import { NAP } from "@/lib/constants";
import { ARTICLES } from "@/lib/articles";
import { SILO_PAGES } from "@/lib/silo";
import { STATES } from "@/lib/states";
import { industrySlugs } from "@/lib/industries";

const base = NAP.websiteUrl;
const now = new Date();

// 0 = pages, 1 = locations (state + city hubs), 2 = services (city x service),
// 3 = blog. One sub-sitemap each, all rolled up under the /sitemap.xml index.
export async function generateSitemaps() {
  return [{ id: 0 }, { id: 1 }, { id: 2 }, { id: 3 }];
}

const SITELINKS_TARGETS = new Set([
  "/industries",
  "/locations",
  "/about",
  "/insights",
  "/contact"
]);

function pagesSitemap(): MetadataRoute.Sitemap {
  const staticPaths = [
    "", "/about", "/contact", "/services", "/locations",
    "/careers", "/insights", "/blog", "/quote", "/pricing", "/reviews",
    "/industries", "/privacy", "/terms"
  ];
  const staticEntries = staticPaths.map((p) => ({
    url: `${base}${p}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: p === "" ? 1.0 : SITELINKS_TARGETS.has(p) ? 0.9 : 0.7
  }));
  const serviceEntries = SERVICES.map((s) => ({
    url: `${base}/services/${s.slug}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.8
  }));
  const articleEntries = ARTICLES.map((a) => ({
    url: `${base}/insights/${a.slug}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6
  }));
  const industryEntries = industrySlugs().map((i) => ({
    url: `${base}/industries/${i.slug}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.7
  }));
  return [...staticEntries, ...serviceEntries, ...industryEntries, ...articleEntries];
}

function locationsSitemap(): MetadataRoute.Sitemap {
  const stateHubs = STATES.map((s) => ({
    url: `${base}/locations/${s.slug}/`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.8
  }));
  const cityHubs = SILO_PAGES.filter((p: any) => p.type === "city_hub").map(
    (p: any) => ({
      url: `${base}${p.url}/`,
      lastModified: now,
      changeFrequency: "weekly" as const,
      priority: 0.8
    })
  );
  return [...stateHubs, ...cityHubs];
}

function servicesSitemap(): MetadataRoute.Sitemap {
  return SILO_PAGES.filter((p: any) => p.type === "service_in_city").map(
    (p: any) => ({
      url: `${base}${p.url}/`,
      lastModified: now,
      changeFrequency: "weekly" as const,
      priority: 0.6
    })
  );
}

function blogSitemap(): MetadataRoute.Sitemap {
  return SILO_PAGES.filter((p: any) => p.type === "blog").map((p: any) => ({
    url: `${base}${p.url}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.5
  }));
}

export default function sitemap({
  id
}: {
  id: number;
}): MetadataRoute.Sitemap {
  switch (id) {
    case 1:
      return locationsSitemap();
    case 2:
      return servicesSitemap();
    case 3:
      return blogSitemap();
    default:
      return pagesSitemap();
  }
}
