// AUTO-GENERATED by local-authority-silo-engine for Langford Staffing.
// This sitemap replaces the prior cities/silo entries with the new flat silo
// URL structure. Legacy /locations/{city}/ routes redirect via vercel.json.
import type { MetadataRoute } from "next";
import { SERVICES } from "@/lib/services";
import { NAP } from "@/lib/constants";
import { ARTICLES } from "@/lib/articles";
import { SILO_PAGES } from "@/lib/silo";
import { CITIES } from "@/lib/cities";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = NAP.websiteUrl;
  const now = new Date();

  const staticPaths = [
    "",
    "/about",
    "/contact",
    "/services",
    "/locations",
    "/careers",
    "/positions",
    "/insights",
    "/blog",
    "/quote",
    "/pricing",
    "/reviews",
    "/industries",
    "/privacy",
    "/terms"
  ];

  const staticEntries = staticPaths.map((p) => ({
    url: `${base}${p}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: p === "" ? 1.0 : 0.7
  }));

  const serviceEntries = SERVICES.map((s) => ({
    url: `${base}/services/${s.slug}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.8
  }));

  const siloFlatEntries = SILO_PAGES.filter((p: any) => p.type !== "blog").map((p: any) => ({
    url: `${base}${p.url}/`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: p.type === "city_hub" ? 0.8 : 0.6
  }));

  const siloBlogEntries = SILO_PAGES.filter((p: any) => p.type === "blog").map((p: any) => ({
    url: `${base}${p.url}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.5
  }));

  const articleEntries = ARTICLES.map((a) => ({
    url: `${base}/insights/${a.slug}/`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6
  }));

  return [
    ...staticEntries,
    ...serviceEntries,
    ...siloFlatEntries,
    ...siloBlogEntries,
    ...articleEntries
  ];
}
