// AUTO-GENERATED by local-authority-silo-engine for Langford Staffing.
// Catch-all flat route for /{city}-{state}-{service} and /{city}-{state}-staffing-agency
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowRight, ChevronRight, MapPin, Phone, ExternalLink, Building2 } from "lucide-react";
import CTASection from "@/components/CTASection";
import SectionHeading from "@/components/SectionHeading";
import SchemaJsonLd from "@/components/SchemaJsonLd";
import { BRAND, NAP } from "@/lib/constants";
import { editorial } from "@/lib/images";
import { breadcrumbSchema, localBusinessSchema, faqSchema } from "@/lib/schema";
import { getStateByAbbr } from "@/lib/states";
import bundle from "@/lib/silo/content.json";

type Params = { params: { city: string; page: string } };

type SiloPage = {
  type: "city_hub" | "service_in_city" | "blog";
  url: string;
  title: string;
  meta_description: string;
  city: string;
  city_key: string;
  state_abbr: string;
  state: string;
  country?: string;
  lat?: number;
  lng?: number;
  intro?: string;
  local_context?: string;
  service_details?: string;
  pay_intro?: string;
  pay_table?: Array<{ title: string; low: number; high: number }>;
  roles?: string[];
  shifts?: string[];
  certs?: string[];
  key_takeaways?: string[];
  longform?: Array<{ heading: string; body: string }>;
  service_slug?: string;
  service_label?: string;
  service_blurb?: string;
  authority_citations?: Array<{ name: string; url: string; context?: string }>;
  authority_citation?: { name: string; url: string; context?: string };
  faq?: Array<{ q: string; a: string }>;
  image: string;
  image_alt: string;
  neighborhoods?: string[];
  jurisdiction?: { body: string; statute: string; url: string };
  city_hub_url?: string;
  national_service_url?: string;
};

const ALL_PAGES = bundle.pages as SiloPage[];
const FLAT_PAGES = ALL_PAGES.filter((p) => p.type !== "blog");


export async function generateStaticParams() {
  return FLAT_PAGES.map((p) => {
    const seg = p.url.replace(/^\//, "").split("/"); // ["locations", state, citypage]
    return { city: seg[1], page: seg[2] };
  });
}

export function generateMetadata({ params }: Params) {
  const page = FLAT_PAGES.find((p) => p.url === `/locations/${params.city}/${params.page}`);
  if (!page) return {};
  // NOTE: layout.tsx title.template already appends "| Langford Staffing".
  // Pass a bare title here to avoid the double suffix.
  return {
    title: page.title,
    description: page.meta_description,
    alternates: { canonical: `${NAP.websiteUrl}${page.url}/` },
    openGraph: {
      title: page.title,
      description: page.meta_description,
      url: `${NAP.websiteUrl}${page.url}/`,
      siteName: BRAND.name,
      type: "website"
    }
  };
}

function buildSchema(page: SiloPage) {
  const url = `${NAP.websiteUrl}${page.url}/`;
  const stateHub = getStateByAbbr(page.state_abbr);
  const graph: any[] = [
    breadcrumbSchema([
      { name: "Home", url: NAP.websiteUrl + "/" },
      ...(stateHub
        ? [{ name: stateHub.name, url: `${NAP.websiteUrl}/locations/${stateHub.slug}/` }]
        : []),
      { name: page.city, url: `${NAP.websiteUrl}${(page as any).city_hub_url || page.url}/` },
      ...(page.type === "service_in_city"
        ? [{ name: page.service_label || "", url }]
        : [])
    ])
  ];

  if (page.type === "city_hub") {
    graph.push(
      localBusinessSchema({
        "@type": "EmploymentAgency",
        name: `${BRAND.name} in ${page.city}`,
        url,
        areaServed: {
          "@type": "City",
          name: page.city,
          containedInPlace: { "@type": "State", name: page.state }
        },
        geo:
          page.lat && page.lng
            ? {
              "@type": "GeoCoordinates",
              latitude: page.lat,
              longitude: page.lng
            }
            : undefined
      })
    );
  } else if (page.type === "service_in_city") {
    graph.push({
      "@context": "https://schema.org",
      "@type": "Service",
      "@id": `${url}#service`,
      name: `${page.service_label} in ${page.city}, ${page.state_abbr}`,
      provider: {
        "@type": "EmploymentAgency",
        name: BRAND.name,
        url: NAP.websiteUrl
      },
      areaServed: { "@type": "City", name: page.city },
      description: page.service_blurb
    });
  }

  if (page.faq && page.faq.length > 0) {
    graph.push(
      faqSchema(page.faq.map((f) => ({ q: f.q, a: f.a })))
    );
  }

  return graph;
}

export default function SiloFlatPage({ params }: Params) {
  const page = FLAT_PAGES.find((p) => p.url === `/locations/${params.city}/${params.page}`);
  if (!page) notFound();

  const cityPages = ALL_PAGES.filter((p) => p.city_key === page.city_key);
  const siblingServices = cityPages.filter(
    (p) => p.type === "service_in_city" && p.url !== page.url
  );
  const cityHub = cityPages.find((p) => p.type === "city_hub");
  const cityBlogs = cityPages.filter((p) => p.type === "blog");
  const stateHub = getStateByAbbr(page.state_abbr);
  const photoKey = "locations-hero";

  return (
    <>
      <SchemaJsonLd data={buildSchema(page)} />

      {/* Hero — editorial briefing band */}
      <section className="relative isolate overflow-hidden bg-brand-navy text-white">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 opacity-[0.06]"
          style={{
            backgroundImage:
              "linear-gradient(to right, rgba(255,255,255,0.5) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.5) 1px, transparent 1px)",
            backgroundSize: "48px 48px"
          }}
        />
        <div className="relative container-prose grid gap-10 pt-12 pb-14 lg:grid-cols-12 lg:gap-12 lg:pt-16 lg:pb-20">
          <div className="lg:col-span-7">
            <nav className="flex flex-wrap items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-white/65">
              <Link href="/" className="text-white/65 no-underline transition hover:text-brand-saffron">
                Home
              </Link>
              <ChevronRight className="h-3 w-3" />
              {stateHub && (
                <>
                  <Link
                    href={`/locations/${stateHub.slug}/`}
                    className="text-white/65 no-underline transition hover:text-brand-saffron"
                  >
                    {stateHub.name}
                  </Link>
                  <ChevronRight className="h-3 w-3" />
                </>
              )}
              {page.type === "service_in_city" && cityHub ? (
                <>
                  <Link
                    href={`${cityHub.url}/`}
                    className="text-white/65 no-underline transition hover:text-brand-saffron"
                  >
                    {page.city}
                  </Link>
                  <ChevronRight className="h-3 w-3" />
                  <span className="text-white/85">{page.service_label}</span>
                </>
              ) : (
                <span className="text-white/85">{page.city}</span>
              )}
            </nav>

            <p className="mt-6 inline-flex items-center gap-2 border border-white/20 bg-white/5 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron">
              <MapPin className="h-3 w-3" />
              {page.city}, {page.state_abbr}
            </p>
            <h1 className="mt-6 max-w-3xl text-display-xl font-semibold text-balance">
              {page.type === "city_hub" ? (
                <>
                  {page.city} Staffing Agency.{" "}
                  <em className="not-italic font-semibold text-brand-saffron">
                    We find, hire, and place talent.
                  </em>
                </>
              ) : (
                <>
                  {page.service_label} in {page.city},{" "}
                  <em className="not-italic font-semibold text-brand-saffron">
                    screened, placed, supported.
                  </em>
                </>
              )}
            </h1>
            <p className="mt-6 max-w-2xl text-[17px] leading-relaxed text-white/85">
              {page.intro}
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link href="/contact/" className="btn-saffron">
                Hire in {page.city}
                <ArrowRight className="h-4 w-4" />
              </Link>
              <a
                href={`tel:${NAP.phoneE164 || ""}`}
                className="btn-ghost-light"
              >
                <Phone className="h-4 w-4" />
                {NAP.phoneDisplay}
              </a>
            </div>
          </div>

          <div className="lg:col-span-5">
            <figure className="relative overflow-hidden border border-white/10 bg-brand-navy-dark">
              <div className="relative aspect-[4/5] w-full">
                <Image
                  src={editorial(photoKey as any)}
                  alt={page.image_alt || ""}
                  fill
                  priority
                  sizes="(min-width: 1024px) 40vw, 100vw"
                  className="object-cover"
                />
              </div>
              <figcaption className="absolute bottom-3 left-3 right-3">
                <span className="bg-brand-navy/75 px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.22em] text-white/85 backdrop-blur-sm">
                  Plate · {page.city}
                </span>
              </figcaption>
            </figure>
          </div>
        </div>
      </section>

      {/* Body — narrative paragraphs */}
      <section className="section">
        <div className="container-prose grid gap-16 lg:grid-cols-12">
          <article className="lg:col-span-8 space-y-12">
            {/* City hubs keep narrative up top. Service pages move all long-form
                prose to the designed block at the very bottom of the page. */}
            {page.local_context && !page.longform && (
              <div>
                <SectionHeading
                  eyebrow="Local market"
                  title={`What the ${page.city} market looks like.`}
                />
                <p className="mt-6 text-[15px] leading-relaxed text-brand-ink">
                  {page.local_context}
                </p>
              </div>
            )}

            {page.service_details && !page.longform && (
              <div>
                <SectionHeading
                  eyebrow={page.type === "city_hub" ? "How we work" : "Our process"}
                  title={
                    page.type === "city_hub"
                      ? `How we staff in ${page.city}.`
                      : `Our ${page.service_label?.toLowerCase()} process.`
                  }
                />
                <div className="mt-6 space-y-4 text-[15px] leading-relaxed text-brand-ink">
                  {page.service_details.split("\n\n").map((para, i) => (
                    <p key={i}>{para}</p>
                  ))}
                </div>
              </div>
            )}

            {/* Per-role pay table — the differentiator no competitor publishes */}
            {page.pay_table && page.pay_table.length > 0 && (
              <div>
                <SectionHeading
                  eyebrow="Pay ranges"
                  title={`${page.service_label} pay in ${page.city}.`}
                />
                {page.pay_intro && (
                  <p className="mt-6 text-[15px] leading-relaxed text-brand-ink">
                    {page.pay_intro}
                  </p>
                )}
                <div className="mt-6 overflow-hidden rounded-lg border border-brand-line">
                  <table className="w-full border-collapse text-[15px]">
                    <thead>
                      <tr className="bg-brand-navy text-white">
                        <th className="px-4 py-3 text-left font-semibold">Role</th>
                        <th className="px-4 py-3 text-right font-semibold">
                          Hourly range
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {page.pay_table.map((r, i) => (
                        <tr
                          key={r.title}
                          className={i % 2 ? "bg-brand-paper" : "bg-white"}
                        >
                          <td className="px-4 py-3 text-brand-navy">{r.title}</td>
                          <td className="px-4 py-3 text-right font-semibold tabular-nums text-brand-navy">
                            ${r.low} to ${r.high}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <p className="mt-3 text-[12px] text-brand-ink-mute">
                  Ranges reflect local market rates and scale with experience,
                  shift, and certifications. Source: U.S. Bureau of Labor
                  Statistics.
                </p>
              </div>
            )}

            {/* Certifications + shifts */}
            {((page.certs && page.certs.length > 0) ||
              (page.shifts && page.shifts.length > 0)) && (
                <div className="grid gap-6 sm:grid-cols-2">
                  {page.certs && page.certs.length > 0 && (
                    <div className="border border-brand-line bg-white p-5">
                      <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                        What we check for
                      </p>
                      <ul className="mt-4 space-y-2 text-[14px] text-brand-ink-soft">
                        {page.certs.map((c) => (
                          <li key={c} className="flex items-start gap-2">
                            <span className="mt-1.5 h-1 w-1 flex-none rounded-full bg-brand-saffron" />
                            {c}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {page.shifts && page.shifts.length > 0 && (
                    <div className="border border-brand-line bg-white p-5">
                      <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                        Shifts we cover
                      </p>
                      <ul className="mt-4 space-y-2 text-[14px] text-brand-ink-soft">
                        {page.shifts.map((c) => (
                          <li key={c} className="flex items-start gap-2">
                            <span className="mt-1.5 h-1 w-1 flex-none rounded-full bg-brand-saffron" />
                            {c}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}

            {page.neighborhoods && page.neighborhoods.length > 0 && (
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                  Neighborhoods we cover in {page.city}
                </p>
                <ul className="mt-6 grid gap-3 sm:grid-cols-2">
                  {page.neighborhoods.slice(0, 6).map((n) => (
                    <li
                      key={n}
                      className="flex items-start gap-3 border border-brand-line bg-white p-4 text-sm leading-relaxed text-brand-ink"
                    >
                      <Building2 className="h-5 w-5 flex-none text-brand-saffron-dark" strokeWidth={1.75} />
                      <span>{n}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {page.type === "city_hub" && siblingServices.length > 0 && (
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                  Services
                </p>
                <h2 className="mt-3 font-display text-[24px] font-semibold text-brand-navy">
                  Staffing services we offer in {page.city}.
                </h2>
                <ul className="mt-6 grid gap-4 sm:grid-cols-2">
                  {siblingServices.map((s) => (
                    <li key={s.url}>
                      <Link
                        href={`${s.url}/`}
                        className="group block h-full border border-brand-line bg-white p-5 no-underline transition hover:border-brand-saffron"
                      >
                        <div className="flex items-center justify-between gap-3">
                          <span className="font-semibold text-brand-navy transition group-hover:text-brand-saffron-dark">
                            {s.service_label} in {page.city}
                          </span>
                          <ArrowRight className="h-4 w-4 flex-none text-brand-ink-mute" />
                        </div>
                        {s.service_blurb && (
                          <p className="mt-2 text-[13px] leading-relaxed text-brand-ink-soft">
                            {s.service_blurb}
                          </p>
                        )}
                      </Link>
                    </li>
                  ))}
                </ul>
                {stateHub && (
                  <Link href={`/locations/${stateHub.slug}/`} className="link-arrow mt-6">
                    See all cities we staff in {stateHub.name}{" "}
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                )}
              </div>
            )}

            {page.type === "service_in_city" && (
              <div className="grid gap-4 sm:grid-cols-2">
                {cityHub && (
                  <Link
                    href={`${cityHub.url}/`}
                    className="block border border-brand-line bg-brand-paper-warm p-5 no-underline transition hover:border-brand-saffron"
                  >
                    <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                      City hub
                    </p>
                    <p className="mt-2 font-semibold text-brand-navy">
                      Staffing in {page.city}
                    </p>
                  </Link>
                )}
                {stateHub && (
                  <Link
                    href={`/locations/${stateHub.slug}/`}
                    className="block border border-brand-line bg-brand-paper-warm p-5 no-underline transition hover:border-brand-saffron"
                  >
                    <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                      State hub
                    </p>
                    <p className="mt-2 font-semibold text-brand-navy">
                      More cities in {stateHub.name}
                    </p>
                  </Link>
                )}
                {siblingServices.slice(0, 3).map((s) => (
                  <Link
                    key={s.url}
                    href={`${s.url}/`}
                    className="block border border-brand-line bg-white p-5 no-underline transition hover:border-brand-saffron"
                  >
                    <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                      Related in {page.city}
                    </p>
                    <p className="mt-2 font-semibold text-brand-navy">
                      {s.service_label}
                    </p>
                  </Link>
                ))}
              </div>
            )}

            {page.faq && page.faq.length > 0 && (
              <div>
                <SectionHeading eyebrow="FAQ" title="Common questions." />
                <div className="mt-6 space-y-4">
                  {page.faq.map((f, i) => (
                    <details
                      key={i}
                      className="border border-brand-line bg-white p-5"
                    >
                      <summary className="font-semibold text-brand-navy cursor-pointer">
                        {f.q}
                      </summary>
                      <p className="mt-3 text-brand-ink-soft">{f.a}</p>
                    </details>
                  ))}
                </div>
              </div>
            )}

            {cityBlogs.length > 0 && (
              <div>
                <SectionHeading
                  eyebrow="Local guides"
                  title={`More from ${page.city}.`}
                />
                <ul className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                  {cityBlogs.map((b) => (
                    <li key={b.url}>
                      <Link
                        href={`${b.url}/`}
                        className="block border border-brand-line bg-white p-5 no-underline transition hover:border-brand-saffron"
                      >
                        <p className="font-semibold text-brand-navy">
                          {b.title}
                        </p>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Long-form SEO content — at the very bottom by design, broken
                into clean, scannable subsections so it reads section by section
                without disturbing the designed page above it. */}
            {page.longform && page.longform.length > 0 && (
              <section className="border-t border-brand-line pt-12">
                <SectionHeading
                  eyebrow="In depth"
                  title={
                    page.type === "city_hub"
                      ? `Staffing in ${page.city}, explained.`
                      : `${page.service_label} in ${page.city}, explained.`
                  }
                />
                {/* Accordions keep the long-form compact: scannable headings,
                    expandable detail. First one open so there is visible copy. */}
                <div className="mt-8 space-y-3">
                  {page.longform.map((sec, idx) => (
                    <details
                      key={sec.heading}
                      open={idx === 0}
                      className="group border border-brand-line bg-white"
                    >
                      <summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-[16px] font-semibold text-brand-navy">
                        {sec.heading}
                        <ChevronRight className="h-4 w-4 flex-none text-brand-saffron-dark transition-transform group-open:rotate-90" />
                      </summary>
                      <div className="space-y-4 px-5 pb-5 text-[15px] leading-relaxed text-brand-ink-soft">
                        {sec.body.split("\n\n").map((para, i) => (
                          <p key={i}>{para}</p>
                        ))}
                      </div>
                    </details>
                  ))}
                </div>
              </section>
            )}
          </article>

          {/* Sidebar */}
          <aside className="lg:col-span-4 space-y-6 lg:sticky lg:top-32 lg:self-start">
            <div className="border border-brand-line bg-brand-navy p-7 text-white">
              <p className="inline-flex border-b border-brand-saffron pb-1 text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron">
                Hire with {BRAND.shortName}
              </p>
              <h3 className="mt-4 font-display text-[20px] font-semibold">
                Local market knowledge in {page.city}.
              </h3>
              <p className="mt-3 text-sm text-white/80">
                A written brief. Screened candidates. We stay involved past the
                start date.
              </p>
              <Link
                href="/contact/"
                className="btn-saffron mt-6 w-full justify-center"
              >
                Tell us about the role
                <ArrowRight className="h-4 w-4" />
              </Link>
              <a
                href={`tel:${NAP.phoneE164 || ""}`}
                className="mt-4 inline-flex w-full items-center justify-center gap-2 text-sm font-medium text-white/85 no-underline transition hover:text-white"
              >
                <Phone className="h-3.5 w-3.5" />
                {NAP.phoneDisplay}
              </a>
            </div>
          </aside>
        </div>
      </section>

      <CTASection
        eyebrow="Next step"
        title={`Hire faster in ${page.city}.`}
        description="Tell us the role, the shift, and the start date. We come back inside a business day with a short list of screened candidates."
        variant="navy"
      />
    </>
  );
}
