// AUTO-GENERATED by local-authority-silo-engine for Langford Staffing.
// Blog post route for /blog/{slug}
import React from "react";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowRight, ChevronRight, MapPin, Phone, ExternalLink } from "lucide-react";
import CTASection from "@/components/CTASection";
import SectionHeading from "@/components/SectionHeading";
import SchemaJsonLd from "@/components/SchemaJsonLd";
import { BRAND, NAP } from "@/lib/constants";
import { editorial } from "@/lib/images";
import { breadcrumbSchema } from "@/lib/schema";
import bundle from "@/lib/silo/content.json";

type Params = { params: { slug: string } };

type SiloPage = {
  type: string;
  url: string;
  title: string;
  meta_description: string;
  city: string;
  city_key?: string;
  state_abbr: string;
  service_label?: string;
  service_slug?: string;
  intro?: string;
  body?: string;
  key_takeaways?: string[];
  authority_citation?: { name: string; url: string; context?: string };
  image: string;
  image_alt: string;
  city_hub_url?: string;
  service_in_city_url?: string;
  topic?: string;
};

const ALL_PAGES = bundle.pages as SiloPage[];
const BLOGS = ALL_PAGES.filter((p) => p.type === "blog");

export const dynamic = "force-static";
export const dynamicParams = false;

export async function generateStaticParams() {
  return BLOGS.map((p) => ({ slug: p.url.replace("/blog/", "") }));
}

export function generateMetadata({ params }: Params) {
  const page = BLOGS.find((p) => p.url === `/blog/${params.slug}`);
  if (!page) return {};
  return {
    title: `${page.title} | ${BRAND.name}`,
    description: page.meta_description,
    alternates: { canonical: `${NAP.websiteUrl}${page.url}/` },
    openGraph: {
      title: page.title,
      description: page.meta_description,
      url: `${NAP.websiteUrl}${page.url}/`,
      siteName: BRAND.name,
      type: "article"
    }
  };
}

function buildSchema(page: SiloPage) {
  return [
    breadcrumbSchema([
      { name: "Home", url: NAP.websiteUrl + "/" },
      { name: "Blog", url: `${NAP.websiteUrl}/blog/` },
      { name: page.title, url: `${NAP.websiteUrl}${page.url}/` }
    ]),
    {
      "@context": "https://schema.org",
      "@type": "Article",
      headline: page.title,
      description: page.meta_description,
      author: { "@type": "Organization", name: BRAND.name },
      publisher: { "@type": "Organization", name: BRAND.name, url: NAP.websiteUrl },
      url: `${NAP.websiteUrl}${page.url}/`
    }
  ];
}

function renderInline(text: string, blockKey: number): React.ReactNode[] {
  const pattern = /\[([^\]]+)\]\(((?:https?:\/\/|\/)[^)]+)\)/g;
  const nodes: React.ReactNode[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  let idx = 0;
  while ((m = pattern.exec(text)) !== null) {
    if (m.index > last) nodes.push(text.slice(last, m.index));
    const [full, label, href] = m;
    void full;
    const isExternal = href.startsWith("http");
    nodes.push(
      isExternal ? (
        <a
          key={`${blockKey}-l${idx++}`}
          href={href}
          target="_blank"
          rel="noopener noreferrer"
          className="font-medium text-brand-navy underline decoration-brand-saffron underline-offset-2 hover:text-brand-saffron-dark"
        >
          {label}
        </a>
      ) : (
        <Link
          key={`${blockKey}-l${idx++}`}
          href={href}
          className="font-medium text-brand-navy underline decoration-brand-saffron underline-offset-2 hover:text-brand-saffron-dark"
        >
          {label}
        </Link>
      )
    );
    last = m.index + m[0].length;
  }
  if (last < text.length) nodes.push(text.slice(last));
  return nodes;
}

function renderBody(md: string) {
  if (!md) return null;
  const blocks = md.split(/\n\n+/);
  return blocks.map((block, i) => {
    if (block.startsWith("## ")) {
      return (
        <h2
          key={i}
          className="mt-10 font-display text-[22px] font-semibold text-brand-navy"
        >
          {renderInline(block.replace(/^##\s+/, ""), i)}
        </h2>
      );
    }
    return (
      <p key={i} className="mt-4 text-[15px] leading-relaxed text-brand-ink">
        {renderInline(block, i)}
      </p>
    );
  });
}

export default function SiloBlogPage({ params }: Params) {
  const page = BLOGS.find((p) => p.url === `/blog/${params.slug}`);
  if (!page) notFound();

  const cityPages = ALL_PAGES.filter((p) => p.city_key === page.city_key);
  const cityHub = cityPages.find((p) => p.type === "city_hub");
  const serviceInCity = cityPages.find(
    (p) => p.type === "service_in_city" && p.service_slug === page.service_slug
  );
  const relatedBlogs = cityPages
    .filter((p) => p.type === "blog" && p.url !== page.url)
    .slice(0, 3);

  return (
    <>
      <SchemaJsonLd data={buildSchema(page)} />

      <section className="relative isolate overflow-hidden bg-brand-navy text-white">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 opacity-[0.06]"
          style={{
            backgroundImage:
              "linear-gradient(to right, rgba(255,255,255,0.5) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.5) 1px, transparent 1px)",
            backgroundSize: "48px 48px"
          }}
        />
        <div className="relative container-prose pt-12 pb-14 lg:pt-16 lg:pb-20">
          <nav className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-white/65">
            <Link href="/" className="text-white/65 no-underline transition hover:text-brand-saffron">
              Home
            </Link>
            <ChevronRight className="h-3 w-3" />
            <Link href="/blog/" className="text-white/65 no-underline transition hover:text-brand-saffron">
              Blog
            </Link>
            <ChevronRight className="h-3 w-3" />
            <span className="text-white/85">{page.city}</span>
          </nav>

          <p className="mt-6 inline-flex items-center gap-2 border border-white/20 bg-white/5 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron">
            <MapPin className="h-3 w-3" />
            {page.city}, {page.state_abbr}
          </p>
          <h1 className="mt-6 max-w-4xl text-display-xl font-semibold text-balance">
            {page.title}
          </h1>
          {page.meta_description && (
            <p className="mt-6 max-w-3xl text-[17px] leading-relaxed text-white/85">
              {page.meta_description}
            </p>
          )}
        </div>
      </section>

      <section className="section">
        <div className="container-prose grid gap-16 lg:grid-cols-12">
          <article className="lg:col-span-8 space-y-8">
            {page.intro && (
              <p className="text-[16px] leading-relaxed text-brand-ink font-medium">
                {page.intro}
              </p>
            )}
            <div>{renderBody(page.body || "")}</div>

            {page.key_takeaways && page.key_takeaways.length > 0 && (
              <div className="border-l-[3px] border-brand-saffron bg-brand-paper-warm/50 p-7">
                <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-saffron-dark">
                  Key takeaways
                </p>
                <ul className="mt-4 space-y-2 text-[15px] text-brand-ink">
                  {page.key_takeaways.map((k, i) => (
                    <li key={i} className="flex gap-2">
                      <span className="text-brand-saffron-dark">·</span>
                      <span>{k}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {page.authority_citation && page.authority_citation.url && (
              <div>
                <SectionHeading eyebrow="Reference" title="Cited authority." />
                <p className="mt-6 flex gap-3 items-start">
                  <ExternalLink className="h-4 w-4 text-brand-saffron-dark mt-1 flex-none" />
                  <span>
                    <a
                      href={page.authority_citation.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-semibold text-brand-navy underline"
                    >
                      {page.authority_citation.name}
                    </a>
                    {page.authority_citation.context && (
                      <p className="text-sm text-brand-ink-soft mt-1">
                        {page.authority_citation.context}
                      </p>
                    )}
                  </span>
                </p>
              </div>
            )}

            {(cityHub || serviceInCity) && (
              <div>
                <SectionHeading
                  eyebrow="More on this market"
                  title={`Related pages for ${page.city}.`}
                />
                <ul className="mt-6 grid gap-3 sm:grid-cols-2">
                  {cityHub && (
                    <li>
                      <Link
                        href={`${cityHub.url}/`}
                        className="flex items-center justify-between border border-brand-line bg-white px-4 py-3 text-sm font-semibold text-brand-navy no-underline transition hover:border-brand-saffron"
                      >
                        <span>Staffing in {page.city}</span>
                        <ArrowRight className="h-4 w-4 text-brand-ink-mute" />
                      </Link>
                    </li>
                  )}
                  {serviceInCity && (
                    <li>
                      <Link
                        href={`${serviceInCity.url}/`}
                        className="flex items-center justify-between border border-brand-line bg-white px-4 py-3 text-sm font-semibold text-brand-navy no-underline transition hover:border-brand-saffron"
                      >
                        <span>
                          {serviceInCity.service_label} in {page.city}
                        </span>
                        <ArrowRight className="h-4 w-4 text-brand-ink-mute" />
                      </Link>
                    </li>
                  )}
                </ul>
              </div>
            )}

            {relatedBlogs.length > 0 && (
              <div>
                <SectionHeading
                  eyebrow="Local guides"
                  title={`More from ${page.city}.`}
                />
                <ul className="mt-6 grid gap-3">
                  {relatedBlogs.map((b) => (
                    <li key={b.url}>
                      <Link
                        href={`${b.url}/`}
                        className="block border border-brand-line bg-white p-4 no-underline transition hover:border-brand-saffron"
                      >
                        <p className="font-semibold text-brand-navy">{b.title}</p>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </article>

          <aside className="lg:col-span-4 space-y-6 lg:sticky lg:top-32 lg:self-start">
            <div className="border border-brand-line bg-brand-navy p-7 text-white">
              <p className="inline-flex border-b border-brand-saffron pb-1 text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-saffron">
                Hire with {BRAND.shortName}
              </p>
              <h3 className="mt-4 font-display text-[20px] font-semibold">
                Hire faster in {page.city}.
              </h3>
              <p className="mt-3 text-sm text-white/80">
                Tell us the role and the start date. We come back with a short
                list of screened candidates.
              </p>
              <Link
                href="/contact/"
                className="btn-saffron mt-6 w-full justify-center"
              >
                Tell us about the role
                <ArrowRight className="h-4 w-4" />
              </Link>
              <a
                href={`tel:${NAP.phoneE164 || ""}`}
                className="mt-4 inline-flex w-full items-center justify-center gap-2 text-sm font-medium text-white/85 no-underline transition hover:text-white"
              >
                <Phone className="h-3.5 w-3.5" />
                {NAP.phoneDisplay}
              </a>
            </div>
          </aside>
        </div>
      </section>

      <CTASection
        eyebrow="Next step"
        title={`Hire faster in ${page.city}.`}
        description="A written brief, a screened short list, and a coordinator on call. Tell us the role and we will come back inside a business day."
        variant="navy"
      />
    </>
  );
}
